"""BASELINE: the within-parcel run, re-measured under fingerprint.py.

The first version of this test lived in a shell pipe and its numbers are not
reproducible. Re-running it here is not busywork — the across-parcel result is
meaningless unless the two come off the SAME metric.

⚠ AND SKIP p001. It is the ACRIS cover sheet, generated by the county, and it
is identical on all 17 million documents. Fingerprinting it reports that
everything is templatable, which is true and worth nothing: the cover carries
the stamps we already read at L1. The question is about the BODY.
"""
import collections
import csv
import pathlib
import sys

import fingerprint as fp

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = pathlib.Path("pages_out")
BODY = int(sys.argv[1]) if len(sys.argv) > 1 else 3

types = {}
for r in csv.DictReader(open("acris_ledger_1008000049.csv", encoding="utf-8")):
    types[r["document_id"]] = r["doc_type"]

by_type = collections.defaultdict(list)
for d in sorted(ROOT.iterdir()):
    if not d.is_dir():
        continue
    t = types.get(d.name)
    f = fp.page_path(ROOT, d.name, BODY)
    if t and f:
        by_type[t].append((d.name, f))

print(f"WITHIN ONE PARCEL — lot 49, body page p{BODY:03d}")
print(f"metric: row-ink L1, {fp.ROWS} rows, match cutoff {fp.MATCH}")

allpairs = []
for t, items in sorted(by_type.items()):
    if len(items) < 2:
        continue
    allpairs += fp.compare(items, t)

if allpairs:
    m = [p for p in allpairs if p[0] <= fp.MATCH]
    print(f"\n  ALL TYPES POOLED: {len(m)}/{len(allpairs)} pairs matched "
          f"({100*len(m)/len(allpairs):.0f}%)")
    n = sum(len(v) for v in by_type.values() if len(v) >= 2)
    cl = fp.clusters([i for v in by_type.values() if len(v) >= 2 for i in v])
    print(f"  {n} pages -> {len(cl)} clusters   saving {n/len(cl):.2f}x")
