"""Find the ACRIS cover pages, so a layout test never scores them as content.

⚠ THE TRAP THIS EXISTS TO CLOSE, HIT TWICE.

  first time   fingerprinted p001 and every document type came back "fully
               templatable". p001 is the county's Recording and Endorsement
               Cover Page, identical in skeleton on all 17M documents.
  second time  moved to p002/p003/p004, believing "past the cover". IT IS NOT.
               A document with many parties runs the cover to 2, 3 or 4 pages,
               each headed "RECORDING AND ENDORSEMENT COVER PAGE
               (CONTINUATION) — PAGE 2 OF 4". Those pages then formed a
               "cluster of 16" spanning 2014-2025 and three boroughs, which I
               was one step away from reporting as evidence that templates
               repeat citywide.

⚠ THE COVER IS NOT PART OF THE DOCUMENT. It is generated by the City Register
at recording time from the index — the same index that is already free over
Socrata. It carries no term, no covenant, no price the index lacks. Matching it
proves the City uses a form, which nobody doubted, and it inflates every
saving estimate with pages that never needed reading.

HOW IT IS DETECTED — by shape, not by reading. The cover carries a barcode,
and a barcode is not DARK, it is ALTERNATING: a few hundred black-white
transitions across one row. That is the signal. Nothing typed, and no scan
artifact, produces it.

⚠ THE FIRST VERSION OF THIS FILE TESTED DARKNESS AND IT WAS WRONG. "Peak row
ink in the top band" scored 1.000 on pages_out/2015043000681001/p006 — which is
not a cover at all. It is the METES AND BOUNDS DESCRIPTION OF LOT 49, the most
valuable page in the document, and it scored 1.000 because 1970s microfilm
carries a solid black frame across the top of the image.

A solid black band and a barcode are both "dark". They differ completely in
transitions: ~2 against ~400. Testing the wrong one of those two properties
built a filter that would have silently discarded legal descriptions across the
whole corpus while reporting a clean run — this project's signature failure,
caught here only by LOOKING at the page the score flagged.

⚠ AND THE PAGE COUNT IS NOT A PRIOR EITHER. "Skip the first two pages" is the
same mistake in a new costume — the cover is 1 page on a simple deed and 4 on a
multi-party assignment. IT MUST BE DETECTED PER DOCUMENT.
"""
import sys

import numpy as np
from PIL import Image

import fingerprint as fp

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BARCODE_BAND = (0.01, 0.16)   # where the barcode sits, as a fraction of height
# ⚠ SET FROM THE OBSERVED VALLEY, NOT CHOSEN. Distribution over 271 held pages:
#   body pages       150-302   (96 pages)
#   ---- valley      302-356   (3 pages)  <- cutoff goes here
#   cover pages      356-663   (38 pages, and ALL 52 p001 land at 410+)
# Both labelled sets are on the right side: the metes-and-bounds page that broke
# the first detector scores 182; the lowest true cover scores 356.
MIN_TRANSITIONS = 340
BARCODE_INK = (0.25, 0.85)    # a barcode row is dark but NOT solid
COVER_NEAR = 0.45             # distance to a cover exemplar


def barcode_score(path):
    """Max black-white transitions in any row of the top band, normalised.

    ⚠ TRANSITIONS, NOT DARKNESS — see the module docstring for the page this
    correction cost. Measured on this corpus:

        ACRIS barcode row      280-620 transitions
        typed text row          10- 60
        solid microfilm border   0-  4      <- scored 1.000 under "darkness"

    The ink window matters too: a barcode row is 25-85% dark. A row that is
    ~100% dark has no white bars in it, so it is a border, not a barcode.
    """
    im = Image.open(path).convert("L")
    a = np.asarray(im)
    t = fp._otsu(a)
    ink = (a <= t)
    h = ink.shape[0]
    band = ink[int(h * BARCODE_BAND[0]):int(h * BARCODE_BAND[1])]
    if band.size == 0:
        return 0
    trans = np.abs(np.diff(band.astype(np.int8), axis=1)).sum(axis=1)
    dark = band.mean(axis=1)
    ok = (dark >= BARCODE_INK[0]) & (dark <= BARCODE_INK[1])
    return int(trans[ok].max()) if ok.any() else 0


def is_cover(path, exemplars=()):
    """True if this page is a City-generated cover or cover continuation.

    Two independent signals; either is enough. ⚠ DELIBERATELY GENEROUS — a body
    page wrongly dropped costs one page of sample, while a cover page wrongly
    KEPT manufactures exactly the false positive this module exists to prevent.
    """
    b = barcode_score(path)
    if b >= MIN_TRANSITIONS:
        return True, f"barcode {b}"
    if exemplars:
        p = fp.profile(path)
        if p is not None:
            d = min(fp.distance(p, e) for e in exemplars if e is not None)
            if d <= COVER_NEAR:
                return True, f"near-cover {d:.2f}"
    return False, ""
