"""CAN OCR READ THE COVER PAGE EXACTLY? Measured against free ground truth.

⚠ WHY THIS MIGHT BE THE WHOLE GAME. The cover page is not part of the
instrument — it is GENERATED BY THE CITY REGISTER, in one layout, on every
ACRIS document, and it carries: document id, both dates, doc type, every BBL,
both parties with addresses, the CRFN, and the transfer-tax stamps. The stamps
are the real price: RPTT / 2.625% must equal RETT / 0.400%, and on the document
that seeded this work they agreed at $5,923,938 against a recital of $10.

If OCR reads that page exactly, then the single most valuable missing field in
ACRIS — deed consideration, absent from 74.3% of index rows — is recoverable
with NO LANGUAGE MODEL AT ALL, at 20,000 pages/hour.

⚠ AND THE GROUND TRUTH IS FREE. The document id is PRINTED on the cover page
and is also the directory name on disk. So every page grades itself, with no
labelling, at any scale. That is the opposite of the situation that has
distorted this project repeatedly: 25/25 trigger recall meant little because
the triggers were written after reading the pages. Nothing here was written
after seeing the OCR.

⚠ ONE THING THIS CANNOT PROVE. Every document here is 2003+ and born-digital.
35.8% of ACRIS is FT_ microfilm, which may have no City cover page at all and
will not look like this. A pass here is a pass for the modern era only, and
claiming otherwise would repeat the mistake of generalising the template test
from one document type to the whole corpus.
"""
import concurrent.futures as cf
import collections
import json
import os
import pathlib
import re
import statistics
import subprocess
import sys
import time

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import bulk

TESS = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
N = 150

RE_DOCID = re.compile(r"Document\s*ID[:\s]*([0-9A-Z_]{10,20})", re.I)
RE_RPTT = re.compile(r"Real Property Transfer Tax[:\s|$]*([\d,]+\.\d\d)", re.I)
RE_RETT = re.compile(r"Real Estate Transfer Tax[:\s|$]*([\d,]+\.\d\d)", re.I)
RE_CRFN = re.compile(r"CRFN\)?[:\s]*([0-9]{10,16})", re.I)
RE_DATE = re.compile(r"Document Date[:\s]*(\d\d-\d\d-\d{4})", re.I)


def ocr(path):
    r = subprocess.run([TESS, str(path), "stdout", "--psm", "6"],
                       capture_output=True, text=True,
                       encoding="utf-8", errors="replace",
                       env={**os.environ, "OMP_THREAD_LIMIT": "1"})
    return r.stdout or ""


def num(s):
    try:
        return float(s.replace(",", ""))
    except (ValueError, AttributeError):
        return None


def one(d):
    p = d / "p001.tif"
    if not p.exists():
        return None
    t = ocr(p)
    m = RE_RPTT.search(t)
    n = RE_RETT.search(t)
    return {
        "doc": d.name,
        "read_id": (RE_DOCID.search(t).group(1) if RE_DOCID.search(t) else None),
        "rptt": num(m.group(1)) if m else None,
        "rett": num(n.group(1)) if n else None,
        "crfn": (RE_CRFN.search(t).group(1) if RE_CRFN.search(t) else None),
        "date": (RE_DATE.search(t).group(1) if RE_DATE.search(t) else None),
        "chars": len(t),
    }


def main():
    docs = sorted(d for d in pathlib.Path("devr_pages").iterdir()
                  if d.is_dir() and (d / "p001.tif").exists())[:N]
    print(f"{len(docs)} cover pages · 12 procs\n")
    t0 = time.time()
    with cf.ThreadPoolExecutor(12) as ex:
        rows = [r for r in ex.map(one, docs) if r]
    el = time.time() - t0
    print(f"  {len(rows)} pages in {el:.0f}s  ->  {len(rows)/el*3600:,.0f} pg/hr\n")

    # ── 1 · the id grades itself ─────────────────────────────────────────
    exact = sum(1 for r in rows if r["read_id"] == r["doc"])
    found = sum(1 for r in rows if r["read_id"])
    print(f"  DOCUMENT ID read exactly : {exact}/{len(rows)} = {exact/len(rows):.3f}")
    print(f"    (field located at all  : {found}/{len(rows)})")
    bad = [(r["doc"], r["read_id"]) for r in rows
           if r["read_id"] and r["read_id"] != r["doc"]][:5]
    for a, b in bad:
        print(f"      truth {a}  ->  read {b}")

    # ── 2 · the stamps, cross-checked against MASTER.document_amt ────────
    # ⚠ THE INDEX IS USED HERE AS A SECOND WITNESS, NOT AS A SOURCE. The
    # question is whether a value READ FROM THE DOCUMENT is right, and an
    # independent figure that agrees is evidence. Half of DEVR rows carry one.
    ids = [r["doc"] for r in rows]
    mas = {}
    for m in bulk.socrata_in("bnx9-e6tj", "document_id", ids,
                             select="document_id,document_amt"):
        mas.setdefault(m["document_id"], m.get("document_amt"))

    agree = disagree = nocheck = nostamp = 0
    deltas = []
    for r in rows:
        if r["rptt"] is None:
            nostamp += 1
            continue
        price = r["rptt"] / 0.02625
        amt = num(str(mas.get(r["doc"]) or "")) or 0
        if not amt:
            nocheck += 1
            continue
        d = abs(price - amt) / amt
        deltas.append(d)
        if d < 0.005:
            agree += 1
        else:
            disagree += 1
    print(f"\n  RPTT stamp found on cover : {len(rows)-nostamp}/{len(rows)}")
    print(f"    price from stamp vs MASTER.document_amt:")
    print(f"      agree within 0.5%      : {agree}")
    print(f"      DISAGREE               : {disagree}")
    print(f"      no index figure to check against: {nocheck}")
    if deltas:
        print(f"      median relative gap    : {statistics.median(deltas)*100:.3f}%")

    # ── 3 · what this would unlock ───────────────────────────────────────
    print(f"\n  at {len(rows)/el*3600:,.0f} pg/hr, ONE cover page per document:")
    for label, n in [("all DEED (3,646,068)", 3_646_068),
                     ("all MTGE (4,220,709)", 4_220_709),
                     ("ALL ACRIS (17,065,090)", 17_065_090)]:
        print(f"    {label:<26}{n/(len(rows)/el*3600)/24:>7.1f} days on this machine")
    pathlib.Path("_cover_ocr.json").write_text(json.dumps(rows, indent=1))


if __name__ == "__main__":
    main()
